numpy tutorial from hackerrank

**Task 1:  Arrays**

You are given a space separated list of numbers. 

Your task is to print a reversed NumPy array with the element type float.

**Input Format**

A single line of input containing space separated numbers.

**Output Format**

Print the reverse NumPy array with type float.

**Sample Input**

1 2 3 4 -8 -10

**Sample Output**

[-10.  -8.   4.   3.   2.   1.] 

In [ ]:
import numpy as np
def rev(array):
    arr1=np.array(array,dtype=float)
    arr2=np.array(arr1[::-1])
    return arr2
arr=list(map(float,input().split()))
print(rev(arr))

**Task 2:  Shape and Reshape**

You are given a space separated list of nine integers. Your task is to convert this list into a X NumPy array.

**Input Format**

A single line of input containing  space separated integers.

**Output Format**

Print the X NumPy array.

**Sample Input**

1 2 3 4 5 6 7 8 9

**Sample Output**

[ [ 1 2 3 ]

[ 4 5 6 ]

[ 7 8 9 ] ]

In [ ]:
import numpy as np
def reshape(array):
    arr1=np.array(array,dtype=int)
    arr2=arr1.reshape(3,3)
    return arr2
arr=list(map(float,input().split()))
print(reshape(arr))

**Task 3 : Zeros and Ones**

You are given the shape of the array in the form of space-separated integers, each integer representing the size of different dimensions, your task is to print an array of the given shape and integer type using the tools numpy.zeros and numpy.ones.

**Input Format**

A single line containing the space-separated integers.

**Output Format**

First, print the array using the numpy.zeros tool and then print the array with the numpy.ones tool.

**Sample Input 0**

3 3 3

**Sample Output 0**

[[[0 0 0]

  [0 0 0]
  
  [0 0 0]]


---



 [[0 0 0]
 
  [0 0 0]
  
  [0 0 0]]
  

---



 [[0 0 0]
 
  [0 0 0]
  
  [0 0 0]]]
  
  

---


  
[[[1 1 1]

  [1 1 1]
  
  [1 1 1]]
  

---



 [[1 1 1]
 
  [1 1 1]
  
  [1 1 1]]
  


---


 [[1 1 1]
 
  [1 1 1]
  
  [1 1 1]]]

In [ ]:
import numpy as np
def zerosandones(arr):
    arr1=np.array(arr)
    arr2=np.zeros(arr1,int)
    arr3=np.ones(arr1,int)
    return arr2,arr3
arr=list(map(int,input().split()))
r1,r2=zerosandones(arr)
print(r1)
print(r2)

**Task 4 : Array Mathematics**

You are given two integer arrays,  and  of dimensions X. 

Your task is to perform the following operations:

Add ( + )
Subtract ( - )
Multiply ( * )
Integer Division ( / )
Mod ( % )
Power ( ** )

**Input Format**

The first line contains two space separated integers,  and . 
The next  lines contains  space separated integers of array . 
The following  lines contains  space separated integers of array .

**Output Format**

Print the result of each operation in the given order under Task.

**Sample Input**

1 4

1 2 3 4

5 6 7 8

**Sample Output**

[[ 6  8 10 12]]

[[-4 -4 -4 -4]]

[[ 5 12 21 32]]

[[0 0 0 0]]

[[1 2 3 4]]

[[    1    64   2187   65536]] 

Use // for division in Python 3.



In [ ]:
import numpy as np
def array_math(arr3,arr4):
    add=np.add(arr3,arr4)
    sub=np.subtract(arr3, arr4)
    multi=np.multiply(arr3,arr4)
    div=np.floor_divide(arr3, arr4)
    mod=np.mod(arr3,arr4)
    poww=np.power(arr3,arr4)
    return add,sub,multi,div,mod,poww
    
    
lis1=[]
lis2=[]
shape=list(map(int,input().split()))
n=shape[0]
m=shape[1]
for i in range(0,n):
    a=list(map(int,input().split()))
    lis1.append(a)
for i in range(0,n):
    b=list(map(int,input().split()))
    lis2.append(b)
    
arr1=np.array(lis1)
arr2=np.array(lis2)

a,b,c,d,e,f=array_math(arr1,arr2)
print(a)
print(b)
print(c)
print(d)
print(e)
print(f)

2 4

1 2 3 4

1 2 3 4

5 6 7 7

5 6 7 7

**Task 5 : Floor, Ceil and Rint**

**Input Format**

A single line of input containing the space separated elements of array .

**Output Format**

On the first line, print the  of A. 
On the second line, print the  of A. 
On the third line, print the  of A.

**Sample Input**

1.1 2.2 3.3 4.4 5.5 6.6 7.7 8.8 9.9 

**Sample Output**

[ 1.  2.  3.  4.  5.  6.  7.  8.  9.]

[  2.   3.   4.   5.   6.   7.   8.   9.  10.]

[  1.   2.   3.   4.   6.   7.   8.   9.  10.]

**But I had to cheat in this example, because Hackerank has lost its mind in this exercise, because its asking for weired space throughout,**

**The exercise, which is irrelevant. So I had to sneek in one of the discussion foroums, and get the spacing problem corrected.**

In [ ]:
import numpy as np
np.set_printoptions(sign=' ')
arr=list(map(float,input().split()))
array=np.array(arr)
arr1=np.floor(array)
arr2=np.ceil(array)
arr3=np.rint(array)
print(arr1)
print(arr2)
print(arr3)

**Task 6 : Mean, Var, and Std**
 
<b>I would like to tell you guys one thing, is that I kind cheated for a reason, I was not geting how to take the input of the arrays uding for loop,
but multiple input using loops, so I had take the help of the discussion forums.
</b>

You are given a 2-D array of size X. 
Your task is to find:

The mean along axis 
The var along axis 
The std along axis 

**Input Format**

The first line contains the space separated values of  and . 
The next  lines contains  space separated integers.

**Output Format**

First, print the mean. 
Second, print the var. 
Third, print the std.

**Sample Input**

2 2
1 2
3 4

**Sample Output**

[ 1.5  3.5]

[ 1.  1.]

1.11803398875

In [9]:
import numpy as np

np.set_printoptions(legacy='1.13')
lis=list(map(int,input().split()))

n_row,n_col=lis[0],lis[1]

lis1=[]

for i in range(n_row):
    
    lis1.append(list(map(float,input().split())))
    
arr=np.array(lis1)

print(np.mean(arr,axis=1))

print(np.var(arr,axis=0))
print(np.std(arr,axis=None))
      
#print(round(np.std(arr,axis=None),11))

2 2
1 2
3 4
[ 1.5  3.5]
[ 1.  1.]
1.11803398875


**Task 7 :  Sum and Prod**

You are given a 2-D array with dimensions X. 
Your task is to perform the  tool over axis  and then find the  of that result.

**Input Format**

The first line of input contains space separated values of  and . 
The next  lines contains  space separated integers.

**Output Format**

Compute the sum along axis . Then, print the product of that sum.

**Sample Input**

2 2
1 2
3 4

**Sample Output**

24

Explanation

The sum along axis 0 = [4 6] 

The product of this sum = 24

In [11]:
import numpy as np


lis=list(map(int,input().split()))


n_row=lis[0]

n_col=lis[1]

mother_list=[]

for i in range(n_row):
    
    lis1=list(map(int,input().split()))
    
    mother_list.append(lis1)
    
array=np.array([mother_list])

array_sum=np.sum(array,axis=1)

array_prod=np.prod(array_sum)

print(array_prod)

2 2
1 2
3 4
24


**Task 8 : Eye and Identity**


Your task is to print an array of size X with its main diagonal elements as 's and 's everywhere else.

**Input Format**

N denotes rows
M demotes coloumns

**Output Format**

Print the desired N X M array.

**Sample Input**

3 3

**Sample Output**

[[ 1.  0.  0.]

 [ 0.  1.  0.]
 
 [ 0.  0.  1.]]

In [28]:
import numpy as np

n,m=map(int,input().split())

np.set_printoptions(sign=' ')

res=np.eye(n,m,k=0)

print(res)

3 3
[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


Task 9 : Linear Algebra

You are given a square matrix  with dimensions X. Your task is to find the determinant.

**Input Format**

The first line contains the integer . 
The next  lines contains the  space separated elements of array .

**Output Format**

Print the determinant of .

**Sample Input**

2
1.1 1.1
1.1 1.1

**Sample Output**

0.0

In [46]:
import numpy as np

np.set_printoptions(legacy="1.13")

n_row=int(input())

mother_list=[]

for i in range(n_row):
    
    lis1=list(map(float,input().split()))
    
    mother_list.append(lis1)
    
array=np.array(mother_list)

det_array=np.linalg.det(array)

print(det_array)

2
1.1 1.1
1.1 1.1
0.0


**Task 10 : Inner and Outer**

You are given two arrays:  and . 
Your task is to compute their inner and outer product.

**Input Format**

The first line contains the space separated elements of array . 
The second line contains the space separated elements of array .

**Output Format**

First, print the inner product. 
Second, print the outer product.

**Sample Input**

0 1
2 3

**Sample Output**

3

[[0 0]

 [2 3]]
 

In [52]:

import numpy as np

elem1=list(map(int,input().split()))

elem2=list(map(int,input().split()))

array1=np.array(elem1)

array2=np.array(elem2)

inn=np.inner(array1,array2)

out=np.outer(array1,array2)

print(inn)

print(out)

0 1
2 3
3
[[0 0]
 [2 3]]


**Task 11 : Polynomials**

You are given the coefficients of a polynomial P. 
Your task is to find the value of P at point x.

I**nput Format**

The first line contains the space separated value of the coefficients in P. 
The second line contains the value of x.

**Output Format**

Print the desired value.

**Sample Input**

1.1 2 3

0

**Sample Output**

3.0

In [56]:
np.polyval(list(map(float,input().split())),float(input()))

1.1 2 3
0


3.0

**Task 12 : Dot and Cross**

You are given two arrays A and B. Both have dimensions of X. 

Your task is to compute their matrix product.

**Input Format**

The first line contains the integer N. 
The next  lines N contains N space separated integers of array A . 
The following N lines contains N space separated integers of array B .

**Output Format**

Print the matrix multiplication of A  and B.

**Sample Input**

2

1 2

3 4

1 2

3 4

**Sample Output**

[[ 7 10]

 [15 22]]

In [14]:
import numpy as np
n=int(input())

A=np.array([list(map(int,input().split())) for i in range(n)])

B=np.array([list(map(int,input().split())) for i in range(n)])

out=np.dot(A,B)

print(out)

2
1 2
3 4
1 2
3 4
[[ 7 10]
 [15 22]]


**Task 13 : Concatenate**

You are given two integer arrays of size N X P and M X P (N & M are rows, and P is the column). 
Your task is to concatenate the arrays along axis 0.

**Input Format**

The first line contains space separated integers N, M and P. 
The next N lines contains the space separated elements of the P columns. 
After that, the next M lines contains the space separated elements of the P columns.

**Output Format**

Print the concatenated array of size (N+M)XP.

**Sample Input**

4 3 2

1 2

1 2 

1 2

1 2

3 4

3 4

3 4 

**Sample Output**

[[1 2]

 [1 2]
 
 [1 2]
 
 [1 2]
 
 [3 4]
 
 [3 4]
 
 [3 4]]

In [15]:
import numpy as np

lis=list(map(int,input().split()))

N=lis[0]

M=lis[1]

P=lis[2]

A=np.array([list(map(int,input().split())) for i in range(N)])

B=np.array([list(map(int,input().split())) for i in range(M)])

out=np.concatenate((A,B),axis=0)

print(out)

4 3 2
1 2
1 2
1 2
1 2
3 4
3 4
3 4


**Task 14 : Transpose and Flatten**

You are given a N X M integer array matrix with space separated elements (N = rows and M = columns). 
Your task is to print the transpose and flatten results.

**Input Format**

The first line contains the space separated values of N and M. 
The next  lines contains the space separated elements of M columns.

**Output Format**

First, print the transpose array and then print the flatten.

**Sample Input**

2 2

1 2

3 4

**Sample Output**

[[1 3]

 [2 4]]
 
[1 2 3 4]

In [20]:
import numpy as np 
lis=list(map(int,input().split()))

n=lis[0]

m=lis[1]
A=np.array([list(map(int,input().split())) for i in range(n)])
print(np.transpose(A))
print(A.flatten())

2 2
1 2
3 4
[[1 3]
 [2 4]]
[1 2 3 4]


**Task 15 : Min and Max**

You are given a 2-D array with dimensions N X M. 
Your task is to perform the min function over axis 1 and then find the max of that.

**Input Format**

The first line of input contains the space separated values of N and M . 
The next N lines contains M space separated integers.

**Output Format**

Compute the min along axis 1 and then print the max of that result.

**Sample Input**

4 2

2 5

3 7

1 3

4 0

**Sample Output**

3

**Explanation**

The min along axis 1 = [2, 3, 1, 0]

The max of [2, 3, 1, 0] = 3

In [21]:
import numpy as np 

lis=list(map(int,input().split()))

n=lis[0]

m=lis[1]

A=np.array([list(map(int,input().split())) for i in range(n)])

A_min=np.min(A,axis=1)

A_max=np.max(A_min)

print(A_max)

4 2
2 5
3 7
1 3
4 0
3
